What is Linear Regression?

Linear Regression is used when:

Output is continuous (price, marks, salary)

Relationship is roughly linear

Example:

Predict house price based on size (sqft)


2️⃣ The core idea (the equation)

Linear regression assumes this relationship:

𝑦=𝑚𝑥+𝑏

In ML terms:

𝑦^=𝑤𝑋+𝑏

Where:

X → input feature(s)
w → weight (slope)
b → bias (intercept)
ŷ → predicted value
👉 Model learns w and b from data.



In [2]:
## simple Linear Regression

import numpy as np

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 5, 7, 11])

w = 0
b = 0
learning_rate = 0.01

for epoch in range(1000):
    y_pred = w * x + b
    error = y_pred - y
    w_grad = (2/len(x)) * np.dot(error, x)
    b_grad = (2/len(x)) * np.sum(error)
    w -= learning_rate * w_grad
    b -= learning_rate * b_grad

print("Trained weights:", w , "bias:", b)    

Trained parameters: w = 2.18599815406887, b = -0.9494488934269667


In [6]:
from sklearn.linear_model import LinearRegression


In [ ]:
import pandas as pd

X = np.array([[1], [2], [3], [4], [5], [6]])
y = np.array([3, 5, 7, 9, 11, 13])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[9]]))
print("Weights:", model.coef_, "Bias:", model.intercept_)



[19.]


In [12]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data[:5])
print(iris.target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [13]:
model = LinearRegression()
model.fit(iris.data, iris.target)
print(model.predict([iris.data[0]]))

[-0.08254936]


In [14]:
print("weights:", model.coef_)
print("intercept:", model.intercept_)

weights: [-0.11190585 -0.04007949  0.22864503  0.60925205]
intercept: 0.18649524720624855


In [15]:
from sklearn.linear_model import LinearRegression

In [17]:
import numpy as np

import numpy as np

# House size in square feet
X = np.array([
    [500],
    [800],
    [1000],
    [1200],
    [1500],
    [1800],
    [2000],
    [2200],
    [2500],
    [3000]
])

# House price in lakhs
y = np.array([
    20,
    32,
    40,
    48,
    60,
    72,
    80,
    88,
    100,
    120
])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[1750]]),"Lakhs")  # Predict price for a 1750 sqft house

[70.] Lakhs


In [19]:
print("Weights:", model.coef_, "Bias:", model.intercept_)

Weights: [0.04] Bias: 1.4210854715202004e-14


###

# Steps in Machine Learning for Prediction  
## Using Simple Linear Regression

---

### Step 1: Import the Required Libraries
We import the necessary Python libraries required for numerical computation and machine learning model creation.

- **NumPy**: Used for handling arrays and numerical operations  
- **scikit-learn**: Provides the Linear Regression model

---

### Step 2: Creating the Dataset
In this step, we define:
- **Input feature (X)** → independent variable  
- **Target variable (y)** → dependent variable  

The dataset represents the relationship between input and output values.

---

### Step 3: Creating the Model
Here, we create an instance of the **Linear Regression model**.  
At this stage, the model is empty and has not learned anything from the data.

---

### Step 4: Training the Model
The model is trained using the `.fit(X, y)` method.

During training:
- The model learns the best-fit line  
- It calculates optimal values for **weight (slope)** and **bias (intercept)**  
- The error between predicted and actual values is minimized

---

### Step 5: Making a Prediction
After training, the model can predict output values for new, unseen input data using the `.predict()` method.

---

### Step 6: Accessing Learned Parameters
Once the model is trained, we can access:
- **Coefficient (`coef_`)** → Represents the slope (weight)  
- **Intercept (`intercept_`)** → Represents the bias  

These parameters define the learned linear equation.
